disabled_rules: # rule identifiers to exclude from running
#  - colon
#  - comma
#  - control_statement
#  - file_length
#  - force_cast
#  - force_try
#  - function_body_length
#  - leading_whitespace
#  - opening_brace
#  - operator_whitespace
#  - return_arrow_whitespace
#  - statement_position
#  - todo
#  - trailing_semicolon
#  - type_body_length
#  - type_name
#  - variable_name_max_length
#  - variable_name_min_length
#  - variable_name
# - line_length
# - nesting
  - trailing_newline
  - trailing_whitespace
included: # paths to include during linting. `--path` is ignored if present. takes precendence over `excluded`.
  - FlickrOpenFeedViewer
excluded: # paths to ignore during linting. overridden by `included`.
#  - Carthage
  - Pods
  - FlickrOpenFeedViewerTests
line_length: 150
file_length:
  - 1000
function_body_length:
  - 75
  - 100
type_body_length:
  - 400 # Warning
  - 500 # Error